spring:
  application:
    name: Vale-Ponto
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: "jdbc:postgresql://localhost:5432/db_vale_ponto"
    username: "postgres"
    password: "senha_banco_de_dados"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect